# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed7a304b347d48129fa2bffd427c00ae991e4145e1fdcea14837173e59aeeec8641917a8bb6fb25d895ecb8f14a3e7b16d8b7de530b10eb169d5611d57530aa1

test:
  secret_key_base: ca26cffa8d4cc8dd3e92cfa21246ec66762a770ba9dd23ad2699547f1a7e87cca51d3b9218251f109d5ad6061d9f46c38d6cdcc171f13c7c89a7c4897c140f99

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: ln26cfga9d4cu3dd3e92nfa23249ec66762a780ba9df21bd2690547f1a7e84cca51d3b9218251f119d5ad6061d9f46c38d6cdcc171f13c7c89a7c4897c140f99
